[package]
name = "badmessage"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
automerge = { path = "../automerge" }
criterion = "0.3.5"
json = "0.12.4"
rand = "^0.8"


[[bin]]
name = "badmessage"
doc = false
bench = false

