[workspace]
members = [
    "automerge",
    "automerge-cli",
    "automerge-wasm",
    "automerge-cli",
    "edit-trace",
]

[profile.release]
debug = true
lto = true
opt-level = 3

[profile.bench]
debug = true
