[workspace]

members = [
    "automerge",
    "automerge-c",
    "automerge-cli",
    "automerge-backend",
    "automerge-backend-wasm",
    "automerge-frontend",
    "automerge-cli",
]

[profile.release]
lto = true
