language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
