[package]
name = "automerge-cli"
version = "0.1.0"
authors = ["Orion Henry <orion.henry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
automerge-backend = { path = "../automerge-backend" }

