[package]
name = "edit-trace"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
automerge = { path = "../automerge" }
json = "0.12.4"
rand = "^0.8"
