[package]
name = "automerge"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "^0.4.3"
leb128 = "^0.2.4"
sha2 = "^0.9.5"
rand = { version = "^0.6.5", features = ["wasm-bindgen"] }
thiserror = "^1.0.16"
itertools = "^0.9.0"
flate2 = "^1.0.20"
uuid = { version = "^0.8.2", features=["v4", "wasm-bindgen", "serde"] }
smol_str = "^0.1.17"
tracing = { version = "^0.1.25", features = ["log"] }
nonzero_ext = "^0.2.0"
fxhash = "^0.2"
tinyvec = { version = "^1.3.0", features = ["alloc"] }
unicode-segmentation = "1.7.1"
serde = { version = "^1.0", features=["derive"] }
strum = { version = "0.21.0", features=["derive"]}

[dependencies.web-sys]
version = "^0.3.22"
features = ["console"]

[dev-dependencies]
pretty_assertions = "^0.7.2"
proptest = { version = "0.10.1", default-features = false, features = ["std"] }
serde_json = { version = "^1.0.61", features=["float_roundtrip"], default-features=true }

