[package]
name = "automerge"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "^0.4.3"
thiserror = "1.0.16"
uuid = { version = "^0.5.1", features = ["v4"] }

[dependencies.web-sys]
version = "0.3.22"
features = ["console"]
